version: "3.8"

services:


#######################################
# For a Docker Hub-exclusive workflow #
#######################################

  # db:
  #   image: loganhagen/yoobi-db:latest
  #   volumes:
  #     - data:/data/db

  # posts:
  #   container_name: posts
  #   image: loganhagen/yoobi-posts:latest
  #   env_file:
  #     - ./yoobi-posts/.env

  # yoobi-bot:
  #   container_name: yoobi-bot
  #   image: loganhagen/yoobi-bot:latest
  #   env_file:
  #     - ./yoobi-bot/.env

  # frontend:
  #   container_name: frontend
  #   image: loganhagen/yoobi-frontend:latest
  #   ports: 
  #     - "3000:3000"


##################################
# For using local build contexts #
##################################

  db:
    container_name: db
    build:  
      context: ./yoobi-db
    volumes:
      - data:/data/db

  yoobi-bot:
    container_name: yoobi-bot
    build:
      context: ./yoobi-bot
    volumes:
      - ./yoobi-bot:/app/yoobi-bot
    env_file:
      - ./yoobi-bot/.env

  posts:
    container_name: posts
    build:
      context: ./yoobi-posts
    command: ["./initBackend.sh"]
    ports:
      - "8080:8080"
    volumes:
      - ./yoobi-posts:/app/posts 
    env_file:
      - ./yoobi-posts/.env

  frontend:
    container_name: frontend
    build:
      context: ./yoobi-frontend
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    volumes:
      - ./yoobi-frontend:/app/frontend 
    stdin_open: true
    tty: true

##################################

volumes:
  data:
