version: "3.8"

services:
  db:
    container_name: db
    image: mongo:6
    volumes:
      - data:/data/db

  backend:
    container_name: backend
    build:
      context: ./backend
    command: [ "./initBackend.sh" ]
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app/backend
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
      - MONGO_HOSTNAME=db
      - MONGO_PORT=27017
    depends_on:
      - db

  yoobi:
    container_name: yoobi
    image: loganhagen/yoobi:latest
    env_file:
      - yoobi/.env

  frontend:
    container_name: frontend
    image: loganhagen/yoobi-frontend:latest
    ports: 
      - "3000:3000"
    env_file:
      - frontend/.env

  # For testing without pushing images
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app/frontend
  #   env_file:
  #     - frontend/.env

volumes:
  data:
