version: "3.8"

services:
  mymongodb:
    container_name: db
    image: mongo:6
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=task-management
    networks:
      - b1

  backend:
    container_name: backend
    build:
      context: ./backend
    image: loganhagen/sv2-backend
    command: [ "./initBackend.sh" ]
    volumes:
      - ./backend:/app/backend
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
      - MONGO_HOSTNAME=mymongodb
      - MONGO_PORT=27017
    stdin_open: true
    tty: true
    depends_on:
      - mymongodb
    networks:
      - b1
      - f1

  yoobi:
    container_name: yoobi
    image: loganhagen/yoobi
    env_file:
      - ../yoobi/.env
    networks:
      - f2

  # nhttpd:
  #   build:
  #     context: ../networkTest/nhttpd
  #   stdin_open: true
  #   tty: true

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    image: loganhagen/sv2-frontend
    command: [ "npm", "run", "dev" ]
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    environment:
      - BACKEND_PORT=8080
      - BACKEND_HOST=http://backend
      - YOOBI_PORT=3001
      - YOOBI_HOST=http://yoobi
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - f1
      - f2

networks:
  f1:
    name: f1
  f2:
    name: f2
  b1:
    name: b1

volumes:
  data:
