version: "3.8"

services:
  db:
    container_name: db
    image: mongo:6
    volumes:
      - data:/data/db
    networks:
      - b1

  backend:
    container_name: backend
    build:
      context: ./backend
    image: loganhagen/sv2-backend:latest
    command: [ "./initBackend.sh" ]
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app/backend
    networks:
      - b1
      - f1
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
      - MONGO_HOSTNAME=db
      - MONGO_PORT=27017
    depends_on:
      - db

  yoobi:
    container_name: yoobi
    image: loganhagen/yoobi:latest
    env_file:
      - ../yoobi/.env
    networks:
      - f2

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    image: loganhagen/sv2-frontend:latest
    command: [ "npm", "run", "dev" ]
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    networks:
      - f1
      - f2
    environment:
      - BACKEND_PORT=8080
      - BACKEND_HOST=http://backend
      - YOOBI_PORT=3001
      - YOOBI_HOST=http://yoobi
    depends_on:
      - backend

networks:
  f1:
    name: f1
  f2:
    name: f2
  b1:
    name: b1

volumes:
  data:
