version: "3.8"

services:
  mymongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=task-management

  backend:
    build:
      context: ./backend
    command: [ "./initBackend.sh" ]
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app/backend
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
      - MONGO_HOSTNAME=mymongodb
      - MONGO_PORT=27017
    stdin_open: true
    tty: true
    depends_on:
      - mymongodb

  yoobi:
    image: loganhagen/yoobi
    ports:
      - "3001:3001"
    env_file:
      - ../yoobi/.env

  nhttpd:
    build:
      context: ../networkTest/nhttpd
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
    command: [ "npm", "run", "dev" ]
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    environment:
      - PUBLIC_SERVER_PORT=8080
      - PUBLIC_SERVER_HOST=http://backend
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
