version: "3.8"

services:
  db:
    container_name: db
    image: mongo:6
    volumes:
      - data:/data/db

  backend:
    container_name: backend
    image: loganhagen/yoobi-posts:latest
    env_file:
      - yoobi-posts/.env

  yoobi:
    container_name: yoobi
    image: loganhagen/yoobi:latest
    env_file:
      - yoobi/.env

  frontend:
    container_name: frontend
    image: loganhagen/yoobi-frontend:latest
    ports: 
      - "3000:3000"

volumes:
  data:
