apiVersion: v1
kind: Service
metadata:
  name: yoobi-posts
  labels:
    app: yoobi-posts
spec:
  type: ClusterIP
  selector:
    app: yoobi-posts
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
