apiVersion: v1
kind: Service
metadata:
  name: yoobi-db
  labels:
    app: yoobi-bot
spec:
  type: ClusterIP
  selector:
    app: yoobi-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
