apiVersion: v1
kind: Service
metadata:
  name: yoobi-db
  labels:
    app: yoobi-bot
spec:
  type: ClusterIP
  selector:
    app: yoobi-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yoobi-db
  labels:
    app: yoobi-db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yoobi-db
  template:
    metadata:
      labels:
        app: yoobi-db
    spec:
      containers:
        - name: yoobi-db
          image: mongo
          # resources:
          #   limits:
          #     memory: "500Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 27017
