apiVersion: apps/v1
kind: Deployment
metadata:
  name: yoobi-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yoobi-db
  template:
    metadata:
      labels:
        app: yoobi-db
    spec:
      containers:
      - name: yoobi-db
        image: mongo
        ports:
        - containerPort: 27017
