apiVersion: apps/v1
kind: Deployment
metadata:
  name: yoobi-bot
  labels:
    app: yoobi-bot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yoobi-bot
  template:
    metadata:
      labels:
        app: yoobi-bot
    spec:
      containers:
      - name: yoobi-bot
        image: loganhagen/yoobi-bot:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
        env:
          - name: OPEN_AI
            valueFrom:
              secretKeyRef:
                name: api-key
                key: OPEN_AI

